version: "3.5"
services:
  backend:
    build: 
      args:
        - NODE_ENV=development
      context: ./backoffice
    restart: always
    networks:
      - sawit-net
    environment:
      - NODE_ENV=development
    volumes:
      - ./backoffice:/app/backoffice
    ports:
      - "8000:8000"

networks:
  sawit-net:
    driver: bridge

